#!/bin/bash

# Emoji picker script for rofi

# Create emoji database if it doesn't exist
EMOJI_FILE="$HOME/.config/rofi/emojis.txt"

if [[ ! -f "$EMOJI_FILE" ]]; then
    cat > "$EMOJI_FILE" << 'EOF'
😀 grinning_face
😃 grinning_face_with_big_eyes
😄 grinning_face_with_smiling_eyes
😁 beaming_face_with_smiling_eyes
😆 grinning_squinting_face
😅 grinning_face_with_sweat
🤣 rolling_on_the_floor_laughing
😂 face_with_tears_of_joy
🙂 slightly_smiling_face
🙃 upside_down_face
😉 winking_face
😊 smiling_face_with_smiling_eyes
😇 smiling_face_with_halo
🥰 smiling_face_with_hearts
😍 smiling_face_with_heart_eyes
🤩 star_struck
😘 face_blowing_a_kiss
😗 kissing_face
☺️ smiling_face
😚 kissing_face_with_closed_eyes
😙 kissing_face_with_smiling_eyes
🥲 smiling_face_with_tear
😋 face_savoring_food
😛 face_with_tongue
😜 winking_face_with_tongue
🤪 zany_face
😝 squinting_face_with_tongue
🤑 money_mouth_face
🤗 smiling_face_with_open_hands
🤭 face_with_hand_over_mouth
🤫 shushing_face
🤔 thinking_face
🤐 zipper_mouth_face
🤨 face_with_raised_eyebrow
😐 neutral_face
😑 expressionless_face
😶 face_without_mouth
🙄 face_with_rolling_eyes
😏 smirking_face
😣 persevering_face
😥 sad_but_relieved_face
😮 face_with_open_mouth
🤐 zipper_mouth_face
😯 hushed_face
😪 sleepy_face
😫 tired_face
🥱 yawning_face
😴 sleeping_face
😌 relieved_face
😛 face_with_tongue
👍 thumbs_up
👎 thumbs_down
👌 ok_hand
✌️ victory_hand
🤞 crossed_fingers
🤟 love_you_gesture
🤘 sign_of_the_horns
🤙 call_me_hand
👈 backhand_index_pointing_left
👉 backhand_index_pointing_right
👆 backhand_index_pointing_up
👇 backhand_index_pointing_down
☝️ index_pointing_up
✋ raised_hand
🤚 raised_back_of_hand
🖐️ hand_with_fingers_splayed
🖖 vulcan_salute
👋 waving_hand
🤝 handshake
👏 clapping_hands
🙌 raising_hands
👐 open_hands
🤲 palms_up_together
🔥 fire
💧 droplet
🌊 water_wave
💥 collision
💫 dizzy
💨 dashing_away
🕳️ hole
💣 bomb
💤 zzz
👁️ eye
🗨️ left_speech_bubble
🗯️ right_anger_bubble
💭 thought_balloon
💤 zzz
❤️ red_heart
🧡 orange_heart
💛 yellow_heart
💚 green_heart
💙 blue_heart
💜 purple_heart
🖤 black_heart
🤍 white_heart
🤎 brown_heart
💔 broken_heart
❣️ heart_exclamation
💕 two_hearts
💖 sparkling_heart
💗 growing_heart
💘 heart_with_arrow
💝 heart_with_ribbon
💞 revolving_hearts
💟 heart_decoration
☮️ peace_symbol
✝️ latin_cross
☪️ star_and_crescent
🕉️ om
☸️ wheel_of_dharma
✡️ star_of_david
🔯 dotted_six_pointed_star
🕎 menorah
☯️ yin_yang
☦️ orthodox_cross
🛐 place_of_worship
⛎ ophiuchus
♈ aries
♉ taurus
♊ gemini
♋ cancer
♌ leo
♍ virgo
♎ libra
♏ scorpio
♐ sagittarius
♑ capricorn
♒ aquarius
♓ pisces
🆔 id_button
⚛️ atom_symbol
🉑 japanese_acceptable_button
☢️ radioactive
☣️ biohazard
📴 mobile_phone_off
📳 vibration_mode
🈶 japanese_not_free_of_charge_button
🈚 japanese_free_of_charge_button
🈸 japanese_application_button
🈺 japanese_open_for_business_button
🈷️ japanese_monthly_amount_button
✴️ eight_pointed_star
🆚 vs_button
💮 white_flower
🉐 japanese_bargain_button
㊙️ japanese_secret_button
㊗️ japanese_congratulations_button
🈴 japanese_passing_grade_button
🈵 japanese_no_vacancy_button
🈹 japanese_discount_button
🈲 japanese_prohibited_button
🅰️ a_button_blood_type
🅱️ b_button_blood_type
🆎 ab_button_blood_type
🆑 cl_button
🅾️ o_button_blood_type
🆘 sos_button
❌ cross_mark
⭕ hollow_red_circle
🛑 stop_sign
⛔ no_entry
📛 name_badge
🚫 prohibited
💯 hundred_points
💢 anger_symbol
♨️ hot_springs
🚷 no_pedestrians
🚯 no_littering
🚳 no_bicycles
🚱 non_potable_water
🔞 no_one_under_eighteen
📵 no_mobile_phones
🚭 no_smoking
❗ exclamation_mark
❕ white_exclamation_mark
❓ question_mark
❔ white_question_mark
‼️ double_exclamation_mark
⁉️ exclamation_question_mark
🔅 dim_button
🔆 bright_button
〽️ part_alternation_mark
⚠️ warning
🚸 children_crossing
🔱 trident_emblem
⚜️ fleur_de_lis
🔰 japanese_symbol_for_beginner
♻️ recycling_symbol
✅ check_mark_button
🈯 japanese_reserved_button
💹 chart_increasing_with_yen
❇️ sparkle
✳️ eight_spoked_asterisk
❎ cross_mark_button
🌐 globe_with_meridians
💠 diamond_with_a_dot
Ⓜ️ circled_m
🌀 cyclone
💤 zzz
🏧 atm_sign
🚾 water_closet
♿ wheelchair_symbol
🅿️ p_button
🈳 japanese_vacancy_button
🈂️ japanese_service_charge_button
🛂 passport_control
🛃 customs
🛄 baggage_claim
🛅 left_luggage
🚹 mens_room
🚺 womens_room
🚼 baby_symbol
🚻 restroom
🚮 litter_in_bin_sign
🎦 cinema
📶 antenna_bars
🈁 japanese_here_button
🔣 input_symbols
ℹ️ information
🔤 input_latin_letters
🔡 input_latin_lowercase
🔠 input_latin_uppercase
🔢 input_numbers
#️⃣ keycap_number_sign
*️⃣ keycap_asterisk
⏏️ eject_button
▶️ play_button
⏸️ pause_button
⏹️ stop_button
⏺️ record_button
⏭️ next_track_button
⏮️ last_track_button
⏩ fast_forward_button
⏪ fast_reverse_button
⏫ fast_up_button
⏬ fast_down_button
◀️ reverse_button
🔼 upwards_button
🔽 downwards_button
➡️ right_arrow
⬅️ left_arrow
⬆️ up_arrow
⬇️ down_arrow
↗️ up_right_arrow
↘️ down_right_arrow
↙️ down_left_arrow
↖️ up_left_arrow
↕️ up_down_arrow
↔️ left_right_arrow
↪️ left_arrow_curving_right
↩️ right_arrow_curving_left
⤴️ right_arrow_curving_up
⤵️ right_arrow_curving_down
🔀 twisted_rightwards_arrows
🔁 repeat_button
🔂 repeat_single_button
🔄 counterclockwise_arrows_button
🔃 clockwise_vertical_arrows
🎵 musical_note
🎶 musical_notes
➕ plus
➖ minus
➗ divide
✖️ multiply
♾️ infinity
💲 heavy_dollar_sign
💱 currency_exchange
™️ trade_mark
©️ copyright
®️ registered
〰️ wavy_dash
➰ curly_loop
➿ double_curly_loop
🔚 end_arrow
🔙 back_arrow
🔛 on_arrow
🔝 top_arrow
🔜 soon_arrow
✔️ check_mark
☑️ check_box_with_check
🔘 radio_button
🔴 red_circle
🟠 orange_circle
🟡 yellow_circle
🟢 green_circle
🔵 blue_circle
🟣 purple_circle
⚫ black_circle
⚪ white_circle
🟤 brown_circle
🔺 red_triangle_pointed_up
🔻 red_triangle_pointed_down
🔸 small_orange_diamond
🔹 small_blue_diamond
🔶 large_orange_diamond
🔷 large_blue_diamond
🔳 white_square_button
🔲 black_square_button
▪️ black_small_square
▫️ white_small_square
◾ black_medium_small_square
◽ white_medium_small_square
◼️ black_medium_square
◻️ white_medium_square
⬛ black_large_square
⬜ white_large_square
🟫 brown_square
🟪 purple_square
🟦 blue_square
🟩 green_square
🟨 yellow_square
🟧 orange_square
🟥 red_square
🏁 chequered_flag
🚩 triangular_flag
🎌 crossed_flags
🏴 black_flag
🏳️ white_flag
🏳️‍🌈 rainbow_flag
🏳️‍⚧️ transgender_flag
🏴‍☠️ pirate_flag
EOF
fi

chosen=$(cat "$EMOJI_FILE" | rofi -dmenu -i -p "Emoji" -theme-str 'window {width: 30%;} listview {lines: 20;}')

if [[ -n "$chosen" ]]; then
    emoji=$(echo "$chosen" | cut -d' ' -f1)

    # Copy to clipboard
    if command -v wl-copy >/dev/null; then
        echo "$emoji" | wl-copy
    elif command -v xclip >/dev/null; then
        echo "$emoji" | xclip -selection clipboard
    fi

    notify-send "Emoji Picker" "Copied $emoji to clipboard"
fi